name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      placeholder: What surgical workflow need does this address?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - DICOM Upload & Parsing
        - Volume Viewer (NiiVue)
        - AI Segmentation (TotalSegmentator/MONAI)
        - ROI / Crop Tool
        - Mesh Generation (MeshLib)
        - STL Export
        - UI / Workflow
        - Infrastructure / DevOps
        - Other
